# Generated by Django 4.1.5 on 2023-02-15 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.CharField(max_length=5000)),
                ('name', models.CharField(max_length=90)),
                ('email', models.CharField(max_length=111)),
                ('address', models.CharField(max_length=123)),
                ('address2', models.CharField(max_length=123)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=40)),
                ('zip_code', models.IntegerField()),
            ],
        ),
    ]
