# Generated by Django 4.1.5 on 2023-02-16 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_orderupdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderupdate',
            old_name='uodate_id',
            new_name='update_id',
        ),
    ]
